# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_RIGOL) += hdcode_gpio.o
obj-$(CONFIG_RIGOL) += focaltech_touch/
obj-$(CONFIG_RIGOL) += fg_m2c_gpio.o
obj-$(CONFIG_RIGOL) += spi2pll_lxm2582_gpio.o
obj-$(CONFIG_RIGOL) += afg_gpio.o
obj-$(CONFIG_RIGOL) += spi2afe_gpio.o
